[package]
name = "darwinRust"
version = "0.6.0"
authors = ["overflwn"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
rand = "*"